import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Precache all of the assets generated by your build process.
// Their URLs are injected into the variable below at build time.
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

// -- REMOVED self.skipWaiting() and clientsClaim() --
// This allows 'registerType: prompt' in vite.config.js to control updates correctly.

// --- Firebase Messaging Logic ---
// Scripts for firebase and firebase messaging
importScripts('https://www.gstatic.com/firebasejs/10.10.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.10.0/firebase-messaging-compat.js');

// Initialize the Firebase app in the service worker by passing in the messagingSenderId.
const firebaseConfig = {
    apiKey: "AIzaSyC6Cr8OI7pjTt3t70hrjiSW7kWeZj4jHWc",
    authDomain: "bakeryapp-c4812.firebaseapp.com",
    projectId: "bakeryapp-c4812",
    storageBucket: "bakeryapp-c4812.firebasestorage.app",
    messagingSenderId: "547764804378",
    appId: "1:547764804378:web:e4a425b9e13c826afaaaa3",
    measurementId: "G-26NMR2HTWE"
};

const app = firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
    console.log('[sw.js] Received background message ', payload);
    
    // Customize notification here
    const notificationTitle = payload.notification?.title || 'New Order Received!';
    const notificationOptions = {
        body: payload.notification?.body || 'A new order has been placed.',
        icon: '/assets/icons/android-chrome-192x192.png',
        badge: '/assets/icons/android-chrome-192x192.png',
        tag: 'new-order',
        vibrate: [200, 100, 200, 100, 200],
        data: payload.data,
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
});
